### ISSUE TITLE
`oci pull` doesn't work with quay, ghcr

### ISSUE THREAD

**Issue by allisonkarlitskaya** [allisonkarlitskaya/composefs_experiments#17]
`cfsctl pull` works on all manner of local repositories plus `docker://` repos on `docker.io` but not with quay or ghcr.

For quay it complains about missing blobs.  Normal `skopeo copy` works fine here.

For ghcr it complains about not having the bearer token.  `skopeo copy` is also broken here, but `podman pull` works fine.

**Comment by cgwalters** [comment]
One thing the proxy does is convert legacy docker "v2s2" manifests to OCI automatically which we should probably support turning off. Are you pushing images in v2s2 or OCI? i.e. what does `skopeo inspect --raw docker://quay.io/yourimage` look like?

I actually had the *inverse* problem when I was looking at this in my repo. Are you using [the raw API](https://github.com/cgwalters/composefs-oci-experimental/blob/main/src/repo.rs#L1108) ?

See also https://github.com/cgwalters/composefs-oci-experimental/blob/08a0d864223021ecf56477584f45419c846e0c80/src/repo.rs#L1134

**Comment by allisonkarlitskaya** [comment]
Ya, I copied the code from your repo at first, which meant I was using `get_descriptor()` for the config.  That worked with eg. docker.io/fedora, but broke with quay.io/lis/box and ghcr.io/cockpit-project/tasks.

Now I use the config API:

```rust
            let raw_config = self.proxy.fetch_config_raw(&self.img).await?;
            let config = ImageConfiguration::from_reader(raw_config.as_slice())?;
```

and that works with ghcr.io/cockpit-project/tasks and quay.io/lis/box but not with docker.io/fedora.

It would be lovely if there was one way that worked for both...
